Adding condor support for sysbatcher
DavidMorse/LQ2Analysis pull request #62
Opened 2022-06-17 17:10 UTC by gmadigan

Nearly identical to its counterpart but obviously submits jobs with condor rather than batch.

2022-07-04 14:49 UTC, DavidMorse commented
SysBatcher.py already runs on HTCondor, so I'm not sure why a new file is needed here. As far as I can tell only the year and brag arguments were added, which could easily have been added to SysBatcher.py. Am I missing something?

2022-07-04 18:00 UTC, gmadigan commented
Weird. You're totally right, I must have gotten confused (these are changes I made ages ago that I only now have sorted into a dedicated branch). Did it always use condor? Anyway, I moved the changes to SysBatcher.py and removed the other script, which is reflected in a new commit to this branch.

2022-07-06 08:28 UTC, DavidMorse commented
It runs on Condor since you updated it last year :)

https://github.com/DavidMorse/LQ2Analysis/commit/d94ebb0c767aa1b023a460bbdea8a9524b994278

2022-07-06 08:29 UTC, DavidMorse requested changes

2022-07-06 08:29 UTC, DavidMorse commented on SysBatcher.py
> +for c in ['uujj']:
please just put back the original line commented out so we remember how to add it back later

2022-07-06 13:13 UTC, gmadigan commented on SysBatcher.py
> +for c in ['uujj']:
Ok, I fixed it. See if that looks good.

2022-07-06 15:52 UTC, merged